---
# Source: alameda/charts/executor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alameda-executor
  namespace: alameda
data:
  config.yml: |-
    datahub:
      address: "alameda-datahub.alameda.svc"
      port: 50050
    executor:
      check-cycle: 3   # second
      expire-time: 300 # second
      enable: true