---
# Source: alameda/charts/rabbitmq/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alameda-rabbitmq
  namespace: alameda
  labels:
    app: rabbitmq
    chart: rabbitmq-0.3.0
    release: "alameda"
    heritage: "Tiller"
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
