---
# Source: alameda/charts/rabbitmq/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-rabbitmq 
  namespace: alameda
  labels:
    app: rabbitmq
    chart: rabbitmq-0.3.0
    release: "alameda"
    heritage: "Tiller"
