---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: alameda-grafana
  namespace: alameda
  labels:
    app: grafana
    chart: grafana-3.8.4
    release: alameda-grafana
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000

  selector:
    app: grafana
    release: alameda-grafana
