---
# Source: grafana/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-3.8.4
    heritage: Tiller
    release: alameda-grafana
  name: alameda-grafana
  namespace: alameda
