---
# Source: alameda/charts/evictioner/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alameda-evictioner
  labels:
    app: alameda
    component: alameda-evictioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-evictioner
subjects:
  - kind: ServiceAccount
    name: alameda-evictioner
    namespace: alameda
