---
# Source: alameda/charts/evictioner/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-evictioner
  namespace: alameda
  labels:
    app: alameda
    component: alameda-evictioner
