---
# Source: alameda/charts/admission-controller/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alameda-admission-controller
  labels:
    app: alameda
    component: admission-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-admission-controller
subjects:
  - kind: ServiceAccount
    name: alameda-admission-controller
    namespace: alameda
