---
# Source: alameda/charts/admission-controller/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-admission-controller
  namespace: alameda
  labels:
    app: alameda
    component: admission-controller
