---
# Source: alameda/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alameda-operator
  labels:
    app: alameda
    component: alameda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-operator
subjects:
  - kind: ServiceAccount
    name: alameda-operator
    namespace: alameda
