---
# Source: alameda/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-operator
  namespace: alameda
  labels:
    app: alameda
    component: alameda-operator
