---
# Source: alameda/charts/datahub/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alameda-datahub
  labels:
    app: alameda
    component: alameda-datahub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-datahub
subjects:
  - kind: ServiceAccount
    name: alameda-datahub
    namespace: alameda
