---
# Source: alameda/charts/datahub/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-datahub
  namespace: alameda
  labels:
    app: alameda
    component: alameda-datahub
