apiVersion: v1
kind: Namespace
metadata:
  name: alameda
---
apiVersion: autoscaling.containers.ai/v1alpha1
kind: AlamedaScaler
metadata:
  name: alameda
  namespace: alameda
spec:
  policy: compact
  enableExecution: true
  scalingTool:
    type: vpa
  selector:
    matchLabels:
      app: nginx
