---
# Source: alameda/charts/notifier/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alameda-notifier-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-notifier-role
subjects:
- kind: ServiceAccount
  name: alameda-notifier 
  namespace: alameda
